# Site settings
title: Automate All The Things 
#tag_text: 
description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

# Build settings
markdown: kramdown
exclude: ["README.md", "vendor"]
sass:
  style: compressed
